### ISSUE TITLE
got decoding str is not supported

### ISSUE THREAD

**Issue by focs** [themoken/canto-next#10]
Hi, I just installed canto and I think this must be very simple to solve but I could not find any reference to it.

This is what I get in my daemon-log:

18:50:22 : CANTO-FETCH -> Empty feed, attempt to update.
18:50:22 : CANTO-FETCH -> Empty feed, attempt to update.
18:50:22 : CANTO-FETCH -> Empty feed, attempt to update.
18:50:22 : CANTO-FETCH -> Empty feed, attempt to update.
18:50:22 : CANTO-FETCH -> ERROR: try to parse http://rss.slashdot.org/slashdot/Slashdot, got decoding str is not supported
18:50:22 : CANTO-FETCH -> ERROR: try to parse http://reddit.com/.rss, got decoding str is not supported
18:50:22 : CANTO-FETCH -> ERROR: try to parse http://codezen.org/canto-ng/feed/, got decoding str is not supported

I added one new URL and has the same problem.

Thank you,

EDIT:

I have traced to problem to feedparser but I could not solve it.

I first thought it was a problem of str vs bytes so I appended .encode() to the URL. Then the error became:

17:24:06 : CANTO-FETCH -> Empty feed, attempt to update.
17:24:06 : CANTO-FETCH -> No content in http://codezen.org/canto-ng/feed/: <unknown>:2:-1: Document is empty

and like this with every possible feed. 

Then I tried to use feedparser directly following the examples in http://pythonhosted.org/feedparser/introduction.html but those did not work either:

exemple 1:

> > > import feedparser
> > > d = feedparser.parse('http://feedparser.org/docs/examples/atom10.xml')
> > > Traceback (most recent call last):
> > >   File "<input>", line 1, in <module>
> > >   File "/usr/lib64/python3.2/site-packages/feedparser-5.1.3-py3.2.egg/feedparser.py", line 3745, in parse
> > >     saxparser.parse(source)
> > >   File "/usr/lib64/python3.2/site-packages/drv_libxml2.py", line 189, in parse
> > >     eltName = (_d(reader.NamespaceUri()),\
> > >   File "/usr/lib64/python3.2/site-packages/drv_libxml2.py", line 70, in _d
> > >     return _decoder(s)[0]
> > >   File "/usr/lib64/python3.2/encodings/utf_8.py", line 16, in decode
> > >     return codecs.utf_8_decode(input, errors, True)
> > > TypeError: 'str' does not support the buffer interface

example 2:

> > > import feedparser
> > > d = feedparser.parse('http://feedparser.org/docs/examples/atom10.xml'.encode())
> > > d
> > > {'feed': {}, 'encoding': 'utf-8', 'bozo': 1, 'version': '', 'namespaces': {}, 'entries': [], 'bozo_exception': SAXParseException('Do cument is empty\n',)}

See the difference when using bytes and str.

I have canto-next and feedparser from their git repo.

Can anyone else reproduce this problem?

**Comment by Shgck** [comment]
Still broken here on Debian Jessie. The PyPI package of feedparser, the git version, and the Debian package all seem to still be 5.1.3, which throw this for every feed:

```
14:35:44 : CANTO-FETCH -> ERROR: try to parse http://www.schneier.com/blog/atom.xml, got decoding str is not supported
```

**Comment by potuz** [comment]
Same thing here in a Gentoo system running curses 0.9.4 and daemon 0.9.5 after an update of the following packages 

20151125 10:58:37 PM BRST   === (2 of 30) Compiling/Merging (app-text/xmlto-0.0.26-r1
20151125 10:58:43 PM BRST   === (3 of 30) Compiling/Merging (dev-lang/python-2.7.10-r1
20151125 11:09:07 PM BRST   === (5 of 30) Compiling/Merging (dev-python/snowballstemmer-1.2.0
20151125 11:09:12 PM BRST   === (6 of 30) Compiling/Merging (dev-python/pygments-2.0.2-r1
20151125 11:09:20 PM BRST   === (7 of 30) Compiling/Merging (dev-python/alabaster-0.7.6
20151125 11:09:27 PM BRST   === (8 of 30) Compiling/Merging (dev-python/sphinx_rtd_theme-0.1.9
20151125 11:09:33 PM BRST   === (9 of 30) Compiling/Merging (dev-python/pytz-2015.6
20151125 11:09:39 PM BRST   === (10 of 30) Compiling/Merging (dev-python/markupsafe-0.23
20151125 11:09:45 PM BRST   === (11 of 30) Compiling/Merging (dev-python/reportlab-3.1.44-r2
20151125 11:09:58 PM BRST   === (12 of 30) Compiling/Merging (dev-python/jinja-2.7.3
20151125 11:10:04 PM BRST   === (13 of 30) Compiling/Merging (dev-python/Babel-2.1.1
20151125 11:10:14 PM BRST   === (14 of 30) Compiling/Merging (dev-python/docutils-0.12
20151125 11:11:20 PM BRST   === (15 of 30) Compiling/Merging (dev-python/sphinx-1.3.1-r1

canto has started to throw the same error message about 'str' not supporting buffer interface and therefore does not update.

**Comment by themoken** [comment]
I still have no problem with Arch (feedparser 5.2.1).

Looks like perhaps the relevant feedparser bug is now: https://github.com/kurtmckee/feedparser/issues/30 so you might want to try the simple example in the first post of the bug and then contribute to that issue.

**Comment by potuz** [comment]
Thanks, seems that is the problem, I think it may have been a change in libxml2 that includes drv_libxml2.py but I have not way of debugging that now. Will wait for official patches.

**Comment by potuz** [comment]
For what it's worth, I posted the bug upstream in libxml2 (since it seems that drv_libxml2.py does not work with Python 3) and hasn't been picked up so for those that are hit by this bug a simple workaround is to disable drv_libxml2 explicitly for example in canto_next/fetch.py add the line

feedparser.PREFERRED_XML_PARSERS.remove('drv_libxml2')

after the import feedparser and this will bring canto back to life. I think expat is being picked up as a parser and that one does not have trouble.

**Comment by Narrat** [comment]
Now I'm getting this error too. Will add locally the commit added by posativ, as it isn't in master yet?

**Comment by Narrat** [comment]
Hmm.. Arch did stuff with libxml2 package and I suppose the issue comes from that
https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/libxml2&id=029a5a2b8ed4a85d5ac266f9e27997478d310b80

Kinda like a callup on the py2 bindings
