### ISSUE TITLE
Data format compatibility with other RSS-readers.

### ISSUE THREAD

**Issue by ewancoder** [themoken/canto-next#16]
So when I'm at another house with my friends which are using MS Windows, I need to install VirtualBox, Linux and canto-curses in order to just simply read the news, meanwhile a friend of mine simply evil-smiling and using android app to read his rss. So I want to use RSS on the go (with my smartphone/another OS), but it's impossible with canto (because it's only ncurses and linux). Is it possible to implement / or make plugin for compatibility with other RSS readers?

**Comment by ewancoder** [comment]
Well, what's about Feedly? Did you manage to get it working? There's also a "feednix" rss reader which is ncurses client for work explicitely with feedly if it helps.

**Comment by themoken** [comment]
Checkout the Inoreader plugin I just committed. Feedly just didn't work out.
