### ISSUE TITLE
inoreader support ?

### ISSUE THREAD

**Issue by romaintb** [themoken/canto-next#21]
Hi !

Is there interest, or even someone working on, support for inoreader as backend ?

Cheers

**Comment by themoken** [comment]
I'm looking to do some form of sync with a service, but I was mostly looking at Feedly and dragging my feet because their key system is pretty crap for readers that aren't web-based. I'll take a look at inoreader

**Comment by romaintb** [comment]
Brilliant, thanks. Let me know if I can help

**Comment by themoken** [comment]
Just a v0.1 synchronization plugin into git. Copy it into ~/.canto-ng/plugins, read the top of the file to configure it, and restart the daemon. Thanks for pointing me at Inoreader, it's got a way better API than Feedly.

**Comment by romaintb** [comment]
brilliant, will test asap.
thanks a million for taking the time to look at it !

**Comment by themoken** [comment]
Great, just be aware that it's rough (only been tested on my machine hence the v0.1) and that you have to be running the git version of the daemon as well, as it has a couple of changes required.

**Comment by ewancoder** [comment]
Wow, great! Actually I was monitoring sync-with-service kind of development and waiting for something to come up, so I've seen this thread even before you pointed it out in my feedly thread. Actually I've never used feedly in my life and I just looked into it after you wrote about it. But inoreader is another thing. It has beautiful chromium extension and couple of friends frequently adviced me to go for it (although I have stayed with good old canto-curses he-he). So, awesome! :D

**Comment by ewancoder** [comment]
Didn't work out of the box, "python-requests" package is dependency and this should be noted at least in readme.

**Comment by ewancoder** [comment]
Should you delete all your feeds in ":list" from canto-curses if you put all of them manually in inoreader?

**Comment by themoken** [comment]
Hey Ewan, there's a pretty long read of caveats at the top of the sync-inoreader.py where it notes the requests dependency, and also mentions that Inoreader will be considered the master for feeds and such, so if you want to keep your old canto feeds, you should export them (canto-remote export > feeds.opml) and import them into Inoreader *before* you start the plugin.

I may spend some time wearing down the caveats before I roll up the next release.

**Comment by Muffo** [comment]
Out of curiosity, is the inoreader sync implemented?

**Comment by themoken** [comment]
Should be, in the form of the sync-inoreader plugin:
https://github.com/themoken/canto-next/blob/master/plugins/sync-inoreader.py

I don't actually use Inoreader though, so I couldn't tell you if it's
bit-rotted in the last couple of years.
