### ISSUE TITLE
Dependency conflict for arch linux AUR archive.

### ISSUE THREAD

**Issue by ewancoder** [themoken/canto-next#22]
When you run yaourt -S "canto-next-git canto-curses-git" you get dependency conflict because canto-curses-git installs canto-daemon as depencency, and then you try to install canto-next-git which is conflicting with canto-daemon and throws "canto-next-git and canto-daemon are in conflics". I solved this problem by installing first canto-next-git and only then canto-curses-git. But is there any solution to install these both using oneline-command?

**Comment by themoken** [comment]
I don't control the AUR packages, so I'd mention this on the package comments for the maintainer.

**Comment by ewancoder** [comment]
Well, I thought you might be involved. Anyway, thx for the reply, I'll try contacting AUR maintainer.

**Comment by ewancoder** [comment]
Shit, my browser got out of control and I closed and reopened this issue again :D Anyway, thx for the reply, I though you might be involved in setting the dependencies. I'll try to contact AUR maintaner now.
