### ISSUE TITLE
Please document data storage

### ISSUE THREAD

**Issue by COLABORATI** [themoken/canto-next#29]
Are you using https://docs.python.org/2/library/shelve.html for data storage or am I misreading the source?

**Comment by themoken** [comment]
At one point it did, but using pickle based shelves isn't language independent (i.e. can only be used from Python) and the database features had to be circumvented sometimes (some versions would grow forever without special treatment). So now the code uses gzipped JSON on disk, but still uses a "shelf" style dict to represent it in code.
