### ISSUE TITLE
Installation instructions for Debian

### ISSUE THREAD

**Issue by okdewit** [themoken/canto-next#34]
The website lists this command to add the signature key:
```
curl http://codezen.org/static/canto-pub.gpg | sudo apt-key add –
```
But I think it should be:
```
curl http://codezen.org/static/canto-pub.gpg | sudo apt-key add -
```
The website uses an n-dash, but a terminal only understands the command with a hyphen on the end.

I also had to add the architecture to the source line like this: `deb [arch=amd64] http://codezen.org/debian xenial main`, or it would complain about missing i386 sources.

**Comment by Tsutsukakushi** [comment]
What a horrible idea to add a key like that over regular HTTP.

**Comment by themoken** [comment]
Signing these .debs has been nothing but a pain in the ass =/

Anyway, I updated the instructions, and finally got around to bringing SSL to all of my domains (although it's still not a great idea to go copy pasting keys from random websites).

Now, if only the key itself was worth a damn anymore...
