### ISSUE TITLE
Cannot change update interval

### ISSUE THREAD

**Issue by mxfm** [themoken/canto-next#35]
I cannot change update interval in canto-curses or canto-remote. Canto manual says that update interval can be change by 
:set update.auto.enabled False
:set update.auto.interval 36000

However, canto-daemon ignores these settings. This is visible from network capture dump - daemon very often connects to rss feeds even after settings are changed and daemon is restarted. I suspect that default update value is too low.

By the way, the config/setting part of canto is completely broken - there is now way to look at settings and change them. For example, after setting update changes via :set in canto-curses, these settings are not visible from canto-remote config. Also, the remote config command does not allow to inspect settings. Neither does :help command in curses allows to inspect available settings. Currently, users have no idea what settings are and how they can be changed.

I see only 1 solution to the update problem now - just shut down the daemon after update.

**Comment by themoken** [comment]
Sorry, I missed this report.

Those settings are for canto-curses updating the items that are shown to you. The daemon's fetching frequency is determined by `defaults.rate` or `feed.rate` (see [tweaking feed options](https://codezen.org/canto-ng/manual/#Tweaking-Feed-Options) in the manual).
