### ISSUE TITLE
request: socks/http proxy

### ISSUE THREAD

**Issue by Spacewalker2** [themoken/canto-next#37]
Hello,

first of all canto is the feed reader I ever dreamed of! The usability is one kind of a flow. Thanks for that!

One thing I miss is that canto do not have the ability to communicate through a (socks) proxy. It would be cool to have this ability.
But there is some downside. I experienced that not all feeds work with the proxy settings of other feed readers e.g. the feed of the wiki in my LAN so it should be possible to make an exception for single feeds.

I will become a patron hope this increases the motivation for this feature a little bit ;-)

Edit: Maybe python considers environment variables like [here](https://wiki.archlinux.org/index.php/Proxy_settings#Environment_variables).

**Comment by Spacewalker2** [comment]
It seems I found a workaround but native support would be nicer.

1. Execute `mkdir -p ~/.config/systemd/user`.
2. Adjust proxy settings and execute `sed "s#ExecStart=.*#ExecStart=/usr/bin/bash -c \"export http_proxy='https://192.168.1.42:8080' \&\& export https_proxy=\$http_proxy \&\& export no_proxy='localhost,127.0.0.1,localaddress,.localdomain.com' \&\& canto-daemon -D /home/%u/.config/canto\"#" /usr/lib/systemd/user/canto-daemon.service > ~/.config/systemd/user/canto-daemon.service`.
3. Execute `systemctl --user enable --now canto-daemon.service`.

Maybe there is a better way to define environment variables with systemd but 'Enviroment=' in unit file does not work.

**Comment by themoken** [comment]
=/
I don't really want to touch this officially when urllib2 officially supports getting the `http_proxy/https_proxy` from the environment as you discovered. Sucks that the systemd unit `Environment=` option didn't work but this is more of systemd problem than a Canto one.
