### ISSUE TITLE
Canto-daemon crashes instead of staying up

### ISSUE THREAD

**Issue by kozross** [themoken/canto-next#41]
I'm running canto-daemon on a remote device, and I find it crashes periodically. I've just witnessed such a crash, and I've attached [a zipped up ``daemon-log``](https://github.com/themoken/canto-next/files/2818637/daemon-log.zip). How come this is happening?

**Comment by themoken** [comment]
Closing this on the assumption that it's a symptom of the same issue in #42 since it looks like it's spawning a zillion threads which crushes performance as well as causing the backtrace in this log.
