### ISSUE TITLE
Very poor ARM performance

### ISSUE THREAD

**Issue by kozross** [themoken/canto-next#42]
I'm getting severe delays and outright non-responsiveness when running ``canto-daemon`` on ARM. This manifests itself as the server eating huge resources due to spawning a large number of threads, and the client communication is slow to the point of unusability.

**Comment by kozross** [comment]
I have reproduced it on 0.9.7: [here is the log](https://github.com/themoken/canto-next/files/2822931/daemon-log.zip). I can also say with great certainty that ``multiprocessing.cpu_count()`` is not to blame here, as it returns the very sensible ``2`` on the server machine when tested.

**Comment by themoken** [comment]
The top line of that log is still daemon 0.9.1...

**Comment by kozross** [comment]
Ah, OK. Sorry about that - I'm not very Python-literate. Will read and try again.

**Comment by kozross** [comment]
Sorry for the delay - I was in a different country for the last two weeks. I've modified my version to match, but now I get even weirder behaviour: specifically, canto-curses doesn't even connect to it, and as [the log](https://github.com/themoken/canto-next/files/2874025/daemon-log.zip) indicates, it seems to just time out. For reference, ``canto-curses --version`` outputs the version as 0.9.3 on my machine.

**Comment by themoken** [comment]
That daemon log doesn't look bad, and isn't spawning threads everywhere so I'll call that progress. The curses-log is the file that's probably interesting in this case, but you're also six releases behind there.

Try with canto-curses 0.9.9 and see if you can reproduce. If you can, attach both daemon- and curses-log from the same directory.

**Comment by kozross** [comment]
Alrighty, having tested with canto-curses 0.9.9, I can confirm that performance is fine. It's a little bit slow, but given the (lack of) horsepower on the device, and the fact that I'm running it over an SSH tunnel, I think it's OK. Gonna close this now - thank you for your patience.
