### ISSUE TITLE
Pip build doesn't declare feedparser as a dependency

### ISSUE THREAD

**Issue by kozross** [themoken/canto-next#43]
Specifically evidenced by this:

```
koz@Azis ~ $ sudo -u canto pip show Canto
Name: Canto
Version: 0.9.7
Summary: Next-gen console RSS/Atom reader
Home-page: http://codezen.org/canto-ng
Author: Jack Miller
Author-email: jack@codezen.org
License: GPLv2
Location: /home/canto/.local/lib/python3.6/site-packages
Requires: 
```

This is clearly incorrect, as ``canto-daemon`` relies on ``feedparser`` to do its work. By contrast, consider the examples given [in the docs for ``pip show``][1]. Sure enough, manual execution fails in the expected manner:

```
koz@Azis ~ $ sudo -u canto bash -c 'PATH=/home/canto/.local/bin:${PATH} canto-daemon -v --port=3333 --cache=on'
Traceback (most recent call last):
  File "/home/canto/.local/bin/canto-daemon", line 3, in <module>
    from canto_next.canto_backend import CantoBackend
  File "/home/canto/.local/lib/python3.6/site-packages/canto_next/canto_backend.py", line 18, in <module>
    from .fetch import CantoFetch
  File "/home/canto/.local/lib/python3.6/site-packages/canto_next/fetch.py", line 16, in <module>
    import feedparser
ModuleNotFoundError: No module named 'feedparser'
```

[1]: https://pip.pypa.io/en/stable/reference/pip_show/#examples

**Comment by dvzrv** [comment]
The same is true for `requests` (for inoreader plugin).

**Comment by themoken** [comment]
I updated setup.py with the feedparser dependency, the 0.9.8 version uploaded includes the change. I didn't add requests since it's optional and listed at the top of the inoreader plugin that needs to be hand enabled and configured anyway.
