### ISSUE TITLE
dead?

### ISSUE THREAD

**Issue by Al-Caveman** [themoken/canto-next#44]
is this unmaintained?  last release is  3 yrs ago, and latest commit to master is 2 yrs ago.

**Comment by themoken** [comment]
Dead, maybe, but not unmaintained. I'd still fix it if outside changes broke it, I'd still read issues and pull requests, but I'm not actively working on it either.

**Comment by Al-Caveman** [comment]
curious, what rss reader do you use now?

**Comment by themoken** [comment]
Still canto-curses. It works as well as it did on last release and obviously my workflow is well supported as the author =). Honestly, I'd probably just stop using RSS (like most people) rather than move to a different client.
