### ISSUE TITLE
How can i uninstall canto[next,curses]

### ISSUE THREAD

**Issue by GenesisTMS** [themoken/canto-next#45]
I cannot find an command or option in `setup.py`

thanks

**Comment by themoken** [comment]
There isn't one. If you installed directly with setup.py there isn't an easy way (so I guess `rm -r /usr/lib/python-3.<x>/site-packages/Canto* /usr/bin/canto-* /usr/lib/canto /usr/lib/systemd/user/canto-* /usr/share/man/man1/canto*`).

Sorry, but typically you want to use a package manager, even just Python's own pip, for this.

**Comment by GenesisTMS** [comment]
ok... thanks for answer :)
