### ISSUE TITLE
pypi sdist for release 0.9.8 missing

### ISSUE THREAD

**Issue by dvzrv** [themoken/canto-next#46]
Hi! I package canto-daemon (or canto-next, or canto) for Arch Linux.

Unfortunately the [latest release 0.9.8](https://github.com/themoken/canto-next/releases/tag/v0.9.8) is missing as an sdist tarball on [pypi](https://pypi.org/project/Canto/). It would be very awesome if you could upload it.

btw: all homepage links on the pypi projects for canto/canto-next/canto-curses time out.

**Comment by themoken** [comment]
Should be updated now.

-------- Original Message --------
