### ISSUE TITLE
Feature request: tt-rss sync plugin

### ISSUE THREAD

**Issue by hhm0** [themoken/canto-next#8]
It would be really nice to have a plugin for syncing with <a href="http://tt-rss.org/redmine/projects/tt-rss/wiki/JsonApiReference">`tt-rss`</a>-compatible sync services and servers.

It seems to be mentioned quite a bit for syncing recently, with the scheduled `Google Reader` shutdown. It would be wonderful to use it to sync `canto` with other readers.

It would be awesome to have a plugin for both the server and the client, for client syncing, and for using `canto` as a sync server too!

More info about syncing stuff <a href="https://github.com/rss-sync/Open-Reader-API/blob/master/content/resources.md">here</a>

**Comment by themoken** [comment]
I've lost interest in syncing with TT-RSS, but just put an Inoreader plugin into git and there's an rsync based one too.
